### ISSUE TITLE
Eviter les conflits de .env et docker-compose.yml

### ISSUE THREAD

**Issue by yoannsculo** [jesuisundesdeux/vigilo-backend#15]
J'ai régulièrement des soucis de conflits sur mes .env et docker-compose.yml lors de mes montées de version de vigilo-backend.

- Sur .env avec les options ajoutées / modifiées
- Sur docker-compose.yml avec les ports que j'ai redéfinis moi même qui entrent en conflit régulièrement avec les modifications qui viennent de master.

Je suis encore néophyte en docker, mais je me demande s'il n'y aurait pas moyen de dissocier les configurations par défaut des configs d'instance afin d'éviter des conflits et/ou stash/stash pop systématiques.

Si quelqu'un a une solution, je suis preneur !

**Comment by kentiss34** [comment]
Pour moi vu la tournure qu'à pris le .env, il faudrait un fichier php qui remplace le env avec la définition des variables.
Ce fichier peut être chargé via le volume docker.

**Comment by badele** [comment]
Je rejoins @kentiss34 , il y'a une bonne partie qui devrait aller sur un config.php par exemple. Mais pour autant il ne faut pas abandonner ce fichier

**Comment by kentiss34** [comment]
Fixé dans dernière version
