### ISSUE TITLE
Mise a disposition charte graphique

### ISSUE THREAD

**Issue by LordTsk** [jesuisundesdeux/vigilo-backend#166]
Hello,

Lors de la mise en place de la beta Vigilo pour Amiens, nous n'avons pas trouvé les ressources graphiques permettant de créer un compte twitter semblable aux autres instances (PP par example)
Est-ce possible de les distribuer dans ce git, ou sous une autre forme, afin de faciliter cette étape ?

Merci

**Comment by kentiss34** [comment]
Hello,
Je viens de créer un repo dédié avec les ressources graphiques :
https://github.com/jesuisundesdeux/vigilo-charte-graphique/tree/master/twittter

**Comment by LordTsk** [comment]
Merci beaucoup :)
