### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by mathieuruellan** [jesuisundesdeux/vigilo-backend#172]
Je vois qu'on peut utiliser une image Docker référencée dans docker-compose, mais je ne trouve pas où elle est définie.

**Comment by kentiss34** [comment]
Hello,
Le git est ici https://github.com/jesuisundesdeux/docker-vigilo-backend/tree/php-7.2

**Comment by mathieuruellan** [comment]
Merci.
Effectivement, c'est pas un mode auquel je suis habitué. J'ai plus tendance à voir le docker comme un livrable avec tout ce qu'il faut dedans pour faire tourner le produit (avec donc ici les fichiers php etc.)
Avec un hook pour qu'il se déploie sur dockerhub. Ca permet de faciliter pour tout le monde le déploiement et les mises à jour.
Si je trouve du  temps, je vous ferai une PR.

**Comment by kentiss34** [comment]
Oui effectivement on devrait l'intégrer dans le git vigilo-backend (en n'oubliant pas que le backend doit pouvoir être installé aussi sur un hosting mutualisé sans docker).

**Comment by kentiss34** [comment]
Dockerfile intégré au repo : 
https://github.com/jesuisundesdeux/vigilo-backend/commit/96e82b32416b459be7dde0ae971b57f0aaa7881f
