### ISSUE TITLE
[BUG] Typo pour la mise à jour des villes.

### ISSUE THREAD

**Issue by tatic0** [jesuisundesdeux/vigilo-backend#186]
![typo-vigilo](https://user-images.githubusercontent.com/1496887/70696730-8b08d100-1cc4-11ea-9acb-fc35c5f5d555.PNG)

Allers dans: admin/index.php?page=cities
Ajouter une ville.
"miss a jour"
devrait être 
"mise à jour"

**Comment by kentiss34** [comment]
https://github.com/jesuisundesdeux/vigilo-backend/commit/a52bf2b07d6e5430c5e2706f1d88472bf276539f
