### ISSUE TITLE
[BUG] Problème d'installation 0.0.14

### ISSUE THREAD

**Issue by PierreRust** [jesuisundesdeux/vigilo-backend#190]
**Symptômes :**
lorsqu'on installe une 0.0.14 en suivant la doc, tout semble fonctionner mais une fois installée, la création de zone ne fonctionne pas et l'admin affiche un warning indiquant que la base est en 0.0.13.

**Analyse:**
Le script sql de création de la base est généré correctement par le script python.
Par contre, lorsque ce script est injecté dans mysql, on a une erreur : 
```
2020-02-26 20:15:09+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/sql_migration.sql
2020-02-26 20:15:12 15 [ERROR] InnoDB: Cannot add field `scope_twittercontent` in table `vigilodb`.`obs_scopes` because after adding it, the row size is 8549 which is greater than maximum allowed size (8126 bytes) for a record on index leaf page.
ERROR 1118 (42000) at line 273: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
```
à cause de cette erreur, le script sql n'est pas exécuté jusqu'au bout et laisse la base dans un état bancal. J'ai encore quelques warning ensuite dans les logs mysql, mais je soupçonne qu'ils soient liés à ce premier problème.

**Comment by PierreRust** [comment]
en fait, ça à l'air d'être un doublon de #122
Il faudrait sûrement ajouter ce param dans l'un des scripts...

**Comment by kentiss34** [comment]
Ajout dans le script + la doc pour les upgrade manuels
