### ISSUE TITLE
[bug] problème d'affichage des images sur page Observations

### ISSUE THREAD

**Issue by tounoki** [jesuisundesdeux/vigilo-backend#209]
Le lien sur les images :
`<a href="/generate_panel.php?s=800&token=<?=$result_obs['obs_token'] ?>" target="_blank"><img src="/generate_panel.php?s=200&token=<?=$result_obs['obs_token'] ?>" /></a>`
est cassé quand on a une install dans un sous-dossier du type http://127.0.0.1:8080/vigilo

![Screenshot_2020-10-03 Vigilo - Observations](https://user-images.githubusercontent.com/5383299/94998424-0324e800-05b2-11eb-9c8c-df8dc2c44c48.png)

**Comment by kentiss34** [comment]
https://github.com/jesuisundesdeux/vigilo-backend/pull/210

**Comment by kentiss34** [comment]
Fixé en 0.0.16
