### ISSUE TITLE
[bug] ds install.php

### ISSUE THREAD

**Issue by tounoki** [jesuisundesdeux/vigilo-backend#211]
`require_once("${cwd}/includes/common.php");`
provoque une erreur
fonctionne avec 
`require_once("${cwd}/../includes/common.php");`

+ le header location à l'enregistrement du formulaire renvoie vers https://api-vigilo.velo-utile.fr/install_app/admin/index.php au lieu de https://api-vigilo.velo-utile.fr/admin/index.php

**Comment by kentiss34** [comment]
Vue ensemble, la doc n'avait pas été suivie à la lettre
