### ISSUE TITLE
Oups... une erreur est survenue. TypeError: e.cityname is undefined 

### ISSUE THREAD

**Issue by aca44** [jesuisundesdeux/vigilo-backend#216]
Bonjour 
Problème lorsque l'on souhaite trier les observations à modérer. Apparu subitement
MErci

**Comment by kentiss34** [comment]
Bonjour,

Sur quelle interface cette erreur est elle constatée ? Web / Android / Admin ?

Merci d'avance

**Comment by aca44** [comment]
Bonjour 
sur l'interface public WEB en version admin, quand on choisi de trier les observations non modérées
![image](https://user-images.githubusercontent.com/75043621/100339642-693e5200-2fda-11eb-9ead-6b983a3bf489.png)
![image](https://user-images.githubusercontent.com/75043621/100355724-8da62880-2ff2-11eb-8a09-8d116c5b0d56.png)

Merci de votre aide

**Comment by kentiss34** [comment]
Du coup il faudrait créer l'Issue dans https://github.com/jesuisundesdeux/vigilo-webapp relatif à l'application web !
Merci d'avance !
