### ISSUE TITLE
Status absent dans la réponse de create_resolution

### ISSUE THREAD

**Issue by tcoupin** [jesuisundesdeux/vigilo-backend#228]
La doc indique que la réponse contient un `status`. https://github.com/jesuisundesdeux/vigilo-backend/blob/master/doc/REST_API.md#retour-10

mais la réponse ne contient que le `token` et le `secrtid`

https://github.com/jesuisundesdeux/vigilo-backend/blob/master/app/create_resolution.php#L69

**Comment by qhess34** [comment]
Il s'agit d'un mauvais copié collé de la doc du create_issue. J'ai effacé l'ensemble des status dans les retours.
Cette valeur a été supprimé à partir de la 0.0.10 pour être remplacée par le HTTP code pour valider le succès ou non de la requête..
