### ISSUE TITLE
[SECU] Saler le hashage des mots de passes

### ISSUE THREAD

**Issue by booleon** [jesuisundesdeux/vigilo-backend#229]
Bonjour,

Merci pour votre logiciel, cependant en regardant un peu le code je vois que les mots de passes sont hachés directement en sha-256 sans sel hors il est conseillé d'utiliser du salage pour garantir la sécurité des utilisateurs. Il y a un risque fort d'exposer les mots de passes des utilisateurs en cas de fuite de la base de données.

Bonne journée !

**Comment by YvesPasteur** [comment]
Bonjour @qhess34 
Est-ce qu'on peut fermer cette issue suite à la PR mergée ? Ou si on s'attend à quelque chose en plus ?

**Comment by qhess34** [comment]
Oui c'est bon !
