### ISSUE TITLE
[BUG] Manque les ressources dans le dossier maps

### ISSUE THREAD

**Issue by booleon** [jesuisundesdeux/vigilo-backend#230]
Bonjour,

apparement l'app va chercher le bouton de zoom dans le dossier maps et elle ne s'y trouve pas. J'ai essayé sur mon installation en 0.0.0.16 et on retrouve le même problème pour Arcachon qui doit aussi être avec la dernière version :
![image](https://user-images.githubusercontent.com/22075523/108641533-f8ef8180-749f-11eb-914d-0684ad2682c3.png)

**Comment by qhess34** [comment]
Y a t'il des fichiers dans maps ?
Le répertoire a t'il les droits en écriture ?
Mapquest a t'il été bien configuré?

**Comment by booleon** [comment]
Bonjour, 
il n'y a pas de fichier dans maps, les droits d'écriture sont bien configurés mais peut-être que mapquest ne fonctionne pas. Je vais investiguer d'avantage. Merci du retour :-)

**Comment by booleon** [comment]
Bonjour,

c'est bon, en effet il y avait un espace dans ma clé mapquest, c'était bien entre la chaise et le clavier :-) on a enfin une instance qui marche vraiment bien pour les tests, je pense qu'on va pouvoir rejoindre le réseau prochainement !
Il nous reste du travail d'organisation avant.
