### ISSUE TITLE
[BUG] cityid non obligatoire en entrée de create_issue

### ISSUE THREAD

**Issue by edikabe** [jesuisundesdeux/vigilo-backend#235]
L'instance de Nantes rencontre des soucis avec une erreur côté client web type **"cityname" undefined** à la redescente des signalements. il semblerait que le nom de la ville ne soit pas renseigné sur un enregistrement.
Après avoir scruter le code de création d'issue, je soupçonne le caractère non obligatoire du **cityid** en entrée du service menant logiquement à la résolution du nom de la ville concernée.
Quel est la raison d'un tel choix de ne pas rendre à minima obligatoire ce champ, y a t'il une résolution autre via environnement que j'aurai loupé à un moment ? Ne serait-il pas plus sécurisant de la setter via variable d'environnement directement vu que ce que j'en comprends chaque ville à sa propre instance?

https://github.com/jesuisundesdeux/vigilo-backend/blob/ee326310703a2b41ce39ba056b3636b3464dd974/app/create_issue.php#L76

**Comment by qhess34** [comment]
Les villes ont été rajoutées tardivement sur Vigilo, les applis Android non mis à jour n’envoie donc pas ce champs 
Le choix est donc corrélé à une problématique de retro-compatibilité.

Ce paramètre doit de plus permettre d'envoyer une ville par son id (si listée dans la table des villes) ou par un champs de texte libre (si non trouvée lors de la resolution des coordonnées Nominatim, ou non présent dans la table en question).

Le "cityname undefined" sur l'instance de Nantes, est une erreur non gérée par https://github.com/jesuisundesdeux/vigilo-webapp parce que https://vigilo.placeauvelo-nantes.fr/get_issues.php?scope=44_nantesmetropole est vide.
Le problème se situe donc plus de ce coté là.

Je viens d'ouvrir une issue pour la mise en place d'un message d'erreur plus clair : https://github.com/jesuisundesdeux/vigilo-webapp/issues/77

**Comment by edikabe** [comment]
Merci de ta réactivité, je comprends parfaitement l'histoire de rétro compatibilité.
Est ce que le fait de valoriser par instance la ville directement réglerait pas le soucis ? 
L'erreur que l'on peut voir actuellement en est une autre que celle que l'on a pu observer depuis un moment.
https://vigilo.placeauvelo-nantes.fr/get_issues.php?scope=44_nantesmetropole renvoie bien rien, en revanche en temps normal il arrive que manque le champ **cityname** dans la grappe de sortie, c'est ce bug que je souhaitais évoquer à la base

**Comment by qhess34** [comment]
Les instances couvrent des territoires avec beaucoup de villes. On s'est rendu compte que certaines villes au sein de ces territoires voulaient des exports sur leur localité précise d'où la nécessité d'avoir cette catégorisation.
Le panel d'admin permet de faire les corrections sur les champs villes en erreur, non listés dans la table des villes, ... mais il faut que l'admin fasse une verif/corrections de temps en temps, du coup il vaut mieux garder une valeur erronée à corriger, plutôt qu'une valeur définit qui peut créer la confusion.
Dans tout les cas, ça n'est pas censé provoqué d'erreur sur les applis (au pire une valeur mal renseignée).

Si il manque le champs cityname  dans le JSON retourné par get_issues.php il y a bien un soucis.
Il faudrait que je vois le JSON, et plus de détails pour analyser.

**Comment by edikabe** [comment]
Ok j'avais mal compris et pensais que la ville était liée à l'instance et unique mais il s'agit bien de la ville où à eu lieu l'incident, désolé c'est moi qui me suis embrouillé.. je n'ai pas encore pu constater par moi même la remontée du bug. J'attends que l'instance de Nantes soit de nouveau UP et tenterai de reproduire le cas et fournirai les steps de reproduction si j'y arrive
