### ISSUE TITLE
[BUG] Pas de nom ville affichée dans le dropdown de l'écran "observations" lorsqu'on est connecté en citystaff

### ISSUE THREAD

**Issue by ndenos-nexway** [jesuisundesdeux/vigilo-backend#245]
Pas de nom ville affichée dans le dropdown de l'écran "observations" lorsqu'on est connecté en citystaff.
![image](https://user-images.githubusercontent.com/3995896/133440067-a3ea2cbf-177d-4a8b-a83f-44b60bd20eb7.png)

Les villes sont pourtant bien renseignées en configuration : 

Le citystaff a également accès à la ville dans la configuration de son compte
![Capture](https://user-images.githubusercontent.com/3995896/133440424-429d0151-152e-4700-814f-dc17c2d9a35b.jpg)

**Comment by qhess34** [comment]
La partie citystaff est en cours de refonte, à voir si ca corrige le bug  => https://github.com/jesuisundesdeux/vigilo-backend/pull/244

**Comment by qhess34** [comment]
#247

**Comment by qhess34** [comment]
Fixé par #247
