### ISSUE TITLE
sur l'API get_issues, peut-on voir les demandes approuvés les "x" derniers jours ?

### ISSUE THREAD

**Issue by thomasnoel** [jesuisundesdeux/vigilo-backend#260]
Ceci est plutôt une question qu'une déclaration de bogue ou qu'une demande d'évolution (quoique).

Une ville me demande d'étudier la possibilité de remonter des observations Vigilo dans son système interne (pour dispatch aux services techniques sur la voirie et les équipements).

Pour cela, je pense remonter quotidiennement via get_issues.php les demandes validées depuis 1 journée, avec une requête du genre:

  https://vigilo.placeauvelo-nantes.fr/get_issues.php?since_unit=day&since=1&status=0&approved=1

Mais de ce que je lis dans le code, since / since_unit n'agissent que sur la date de l'observation elle-même, et pas sur la date de son approbation :

```
    if (!is_null($this->sincefilter) && !is_null($this->sinceUnitFilter)) {
      $datetime = '- ' . $this->sincefilter . ' ' . $this->sinceUnitFilter;
      $where .= ' AND obs_time > ' . strtotime($datetime);
    }

```

Ai-je vu juste ?

J'ai en fait également l'impression qu'on ne pourrait pas construire de requête permettant de remonter les demandes « validées depuis x jours » car obs_approved est un booléen, et non la date de l'approbation. J'ai juste aussi ?

Merci par avance pour vos réponses !

**Comment by qhess34** [comment]
Bonjour,

Effectivement, il n'y a pas de date sur les validations mais uniquement sur
le moment correspondant à l'observation
C'est une fonctionnalité pertinente à mon sens, du coup n'hésitez pas à
soumettre une proposition de modification (via une pull request) ;)

Cordialement,

Quentin

**Comment by thomasnoel** [comment]
Merci pour la confirmation.

Je me permets de fermer "mon" ticket, qui était juste une question. Je verrais si notre client a envie de pousser ce développement, auquel cas je ferai un ticket d'évolution plus explicite.
