### ISSUE TITLE
Compte Twitter obligatoire

### ISSUE THREAD

**Issue by patjoub** [jesuisundesdeux/vigilo-backend#264]
Bonjour,
Twitter nous fait des misères et met du temps à valider notre compte .
Est-ce vraiment nécessaire pour le fonctionnement de Vigilo ?
Merci pour votre réponse.
Bonne journée et merci pour votre travail
Patrick

**Comment by qhess34** [comment]
Bonjour,

Non aucune obligation, le compte Twitter est juste là si vous voulez que les observations soient twittées automatiquement à leur validation.

Quentin
