### ISSUE TITLE
Citystaff ne voit aucune observations/résolution

### ISSUE THREAD

**Issue by DanieleSottile** [jesuisundesdeux/vigilo-backend#268]
Je pense savoir d'où vient le problème et je l'ai résolu de mon coté mais j'aimerais en être sur car j'ai vu d'autres échanges ici sur des soucis partialement lié à ça mais j'ai l'impression que les changements n'ont jamais été finalisés.

En gros, avec un compte citystaff on ne voit rien, ni résolutions ni observations, et même ayant spécifié des villes pour l'utilisateur citystaff.

Comme je disais, j'ai déjà fait un fix mais pouvez vous confirmer ce bug ? est-ce que les comptes citystaff chez vous marchent bien ?

**Comment by yodapotatofly** [comment]
J'ai effectivement le même probleme, peux-tu faire une push-request à ce sujet ?

**Comment by DanieleSottile** [comment]
Yes ! Je vais le faire demain ;)

**Comment by DanieleSottile** [comment]
Voilà, PR faite

**Comment by black-puppydog** [comment]
à fermer donc?
