### ISSUE TITLE
Erreur 403 test API X

### ISSUE THREAD

**Issue by afamultimedia** [jesuisundesdeux/vigilo-backend#275]
Bonjour,
Je déploie actuellement vigilo backend pour le département de la Lozère et j'ai rencontré un blocage au test du compte twitter. En effet après avoir créer une App sur X puis créer les clés API et les Tokens, une fois saisis, le test ne fonctionne pas.
La doc étant encore pour Twitter, l'interface et ses possibilités ont pas mal changé. Y a-t-il quelque chose en particulier à faire ?
Merci pour votre aide.

**Comment by qhess34** [comment]
Bonjour,
Les publication sur Twitter ne fonctionnent plus (à cause d'un changement de politique twitter). Cette fonctionnalité sera supprimées dans les futures versions de vigilo.

**Comment by afamultimedia** [comment]
Bonjour,
Merci pour votre retour.
