### ISSUE TITLE
generate_panel ne fonctionne pas lors du premier appel

### ISSUE THREAD

**Issue by tcoupin** [jesuisundesdeux/vigilo-backend#29]
Lorsqu'on fait appel à generate_panel et que l'image n'existe pas en cache, l'image n'est pas renvoyée (cf pj).
![image](https://user-images.githubusercontent.com/7457386/57029839-32a82600-6c43-11e9-96cc-e7e302d67388.png)

en deuxième appel, l'image est bien renvoyée.

Ex : https://dev-vigilo.alwaysdata.net/generate_panel.php?s=155&token=XMCKPXVI

il faut change le paramètre s pour éviter d'avoir le cache.

**Comment by kentiss34** [comment]
Hello,
Peux tu mettre à jour ton backend ? 
Le generate_panel doit retourner du jpeg à présent.

De plus constates tu des erreurs dans les logs ?

**Comment by kentiss34** [comment]
Dans le contenu de l'image il y a l'erreur php :

> <br />
> <b>Warning</b>:  imagecreatefromjpeg(): gd-jpeg: JPEG library reports unrecoverable error: Empty input file in <b>/home/dev-vigilo/vigilo-backend/app/generate_panel.php</b> on line <b>242</b><br />
> <br />
> <b>Warning</b>:  imagecreatefromjpeg(): './maps/XMCKPXVI_zoom.jpg' is not a valid JPEG file in <b>/home/dev-vigilo/vigilo-backend/app/generate_panel.php</b> on line <b>242</b><br />
> <br />
> <b>Warning</b>:  imagesx() expects parameter 1 to be resource, boolean given in <b>/home/dev-vigilo/vigilo-backend/app/generate_panel.php</b> on line <b>248</b><br />
> <br />
> <b>Warning</b>:  imagesy() expects parameter 1 to be resource, boolean given in <b>/home/dev-vigilo/vigilo-backend/app/generate_panel.php</b> on line <b>248</b><br />
> <br />
> <b>Warning</b>:  imagecopymerge() expects parameter 2 to be resource, boolean given in <b>/home/dev-vigilo/vigilo-backend/app/generate_panel.php</b> on line <b>248</b><br />
> IHDR
>

**Comment by kentiss34** [comment]
C'est à cause du fait que la map n'existe pas.

**Comment by tcoupin** [comment]
ok merci
