### ISSUE TITLE
Gérer les script de migration d'une version à l'autre

### ISSUE THREAD

**Issue by badele** [jesuisundesdeux/vigilo-backend#31]
Suite au déploiement de vigilo par différentes associations. Le parc **vigilo** va devenir hétérogène. il faut mettre en place un processus de migration qui permette facilement de migrer d'une version à l'autre.

**Comment by badele** [comment]
Le but du processus est de faciliter la migration d'une version à une autre.

A ce jours, nous utilisons le script suivant => https://github.com/jesuisundesdeux/vigilo-backend/blob/master/scripts/migrateDatabase.py (celui ci génère le script de migration SQL d'une version **Version X** à une version **Version Z**)

Hors, ne serait t'il pas intéressant de faire un script **php** Qui gère l'installation et la migration d'une version à l'autre ?

Ce qui permettrait d'avoir dans certains cas une interaction avec l'utilisateur ?

De mon point de vu je pense que la migration doit pouvoir se faire

- Manuellement (interaction utilisateur)
- Automatiquement (passage de paramètre), pratique pour le déploiement automatique ou test unitaire

**Comment by yoannsculo** [comment]
Je suis complètement d'accord ! :+1: 

Je pense qu'il faudrait également prévoir la possibilité d'exécuter un script php custom de migration (propre à chaque migration comme ce qui existe déjà pour SQL).

Je prends un exemple.

J'aimerais bien rajouter un champ en table indiquant si l'observation est en paysage ou en portrait afin de faciliter le filtrage d'observations au même format notamment pour générer des animation ou bien des rapports. Il y aura donc besoin d'un script de migration SQL pour ajouter le champ **ET** un script php qui va aller ouvrir chaque photo d'observation, regarder les dimensions et renseigner le champ orientation en BDD.

Dans tous les cas en effet avoir la possibilité de faire la migration manuellement et automatiquement serait une bonne idée je trouve.

**Comment by kentiss34** [comment]
A mon sens il y a 3 lots par mise à jour à prendre en compte :
- Le code source : il doit être facilement "écrasable"
Sur un hébergement dédié comme un docker, je ne sais pas trop comment on peut gérer ça de manière automatique.

- Les configurations (config.php) : on doit pouvoir ajouter dans le fichier des nouvelles entrées
Idem qu'en haut, comment procéder à l'ajout auto des nouvelles variables lors des upgrades ?

- La base de données : on doit gérer les différentiels de schema et les éventuelles entrées de configuration
Un script upgrade.php pourrait faire l'affaire (et executer le genre d'opération que cite Yoann)

**Comment by badele** [comment]
> Le code source : il doit être facilement "écrasable"
Sur un hébergement dédié comme un docker, je ne sais pas trop comment on peut gérer ça de manière automatique.

Autant pour l'installation que la mise à jours, je verrais bien l’exécution d'un script `install.php`

Celui ci s'assurerait de la version en cours (ou nouvelle installation) et exécuterait les taches nécessaires pour jouer l'ensemble des migrations.

> Les configurations (config.php) : on doit pouvoir ajouter dans le fichier des nouvelles entrées
Idem qu'en haut, comment procéder à l'ajout auto des nouvelles variables lors des upgrades ?

Idem, c'est le script précédent qui se chargerait d'effectuer la complétion des variables manquantes

> La base de données : on doit gérer les différentiels de schema et les éventuelles entrées de configuration
Un script upgrade.php pourrait faire l'affaire (et executer le genre d'opération que cite Yoann)

Idem, c'est le script précédent qui se chargerait d'effectuer la complétion des variables manquantes

**Comment by kentiss34** [comment]
Pour config.php, le soucis est réglé du coup par la migration de son contenu en base.

**Comment by kentiss34** [comment]
Le principal est fait sur cette issue.
Si besoin on rouvrira individuellement des issues plus précises.
