### ISSUE TITLE
[LICENSING] Choisir une licence pour les photos envoyées par les utilisateurs

### ISSUE THREAD

**Issue by yoannsculo** [jesuisundesdeux/vigilo-backend#4]
Pour cette première issue, j'opte pour le français, considérant que l'application cible pour le moment des villes françaises. Mais je peux basculer sur l'Anglais si vous le souhaitez.

Je pense qu'il serait intéressant pour l'envoi d'observations

- soit de proposer aux utilisateurs de choisir la licence de leur photographie. Avec le soucis de paternité (anonymat) que cela peut causer. Que faire si la personne demande de garder une paternité alors qu'elle est anonyme ?
- soit d'indiquer aux utilisateurs que tout envoi de photo la placera automatiquement dans une licence type Creative Commons avec paternité Vigilo. Ou l'entité / association qui gère l'instance de Vigilo.

Pour exemple, voici le message présenté par Open Food Facts pour l'envoi de photos / données.

> En ajoutant des informations et/ou des photographies, vous acceptez de placer irrévocablement votre contribution sous licence Database Contents Licence 1.0 pour les informations et sous licence Creative Commons Paternité - Partage des conditions initiales à l'identique 3.0 pour les photos. Vous acceptez d'être crédité par les ré-utilisateurs par un lien vers le produit auquel vous contribuez.

- https://opendatacommons.org/licenses/dbcl/1.0/
- https://creativecommons.org/licenses/by-sa/3.0/deed.fr

Qu'en pensez-vous ?

**Comment by kentiss34** [comment]
Très bonne idée ! Pour moi on fait simple, la deuxième option semble la meilleure.
Il faut d'ailleurs prendre en compte le cas des photos de tiers qui peuvent être postées.

A quel niveau doit on intégrer ça (Playstore ? Appli ?) ?

**Comment by yoannsculo** [comment]
Le cas où des photos de tiers vont être postées risque d'être une source de problèmes potentiels.
Comment savoir si la personne qui exige le retrait d'une photo dit vrai ?
Exige-ton une photo de haute résolution au moins équivalente a celle qui a été postée afin de la comparée avec la photo originale ?
Et donc, garde t-on toutes les photos originales au format transmis par l'utilisateur ?
Dans le cas où la photo aurait été "signalée" par son véritable propriétaire, garde t-on l'observation ? Ou floute t-on juste la photo avec un marqueur indiquant que la photo n'était pas autorisée ?

Dans les autres cas normaux j'aurais tendance à mettre un encart bien visible dans le paragraphe avertissement actuel de l'application Android (en plus du message sur la vie privée). On pourrait également le préciser sur le play store et sur les sites web respectifs des instances Vigilo + portail commun vigilo.

Par ailleurs, nous pourrions apposer quelque part sur l'image vigilo générée un symbole Creative Commons.

**Comment by tounoki** [comment]
Honnêtement, on pourrait faire valoir que les photos prises au smartphone pour une illustration (éventuellement avec un gribouillis) ne sont pas des "oeuvres originales" (donc ne déclenchent par de droits de prop intellectuelle -> donc pas de licence spécifique)
`Si le caractère d’originalité ne peut être retenu, alors l’auteur de la photographie ne pourra faire prévaloir ses droits et la photographie peut être utilisée librement.`
Par contre, on peut mettre un CC-BY ou CC-BY-SA sur la carte montée (assemblage logo, mise en page, photo, vue aérienne).

+1 pour les avertissements et pour assurer le coup si à l'occasion il y a une ou 2 photos franchement dignes de propriété intellectuelle. Mais en cas de réclamation, c'est la non-originalité qui doit être le premier argument.

**Comment by kentiss34** [comment]
Hello,
Merci pour ces infos, je cc @polomarcus qui a plus d'infos que moi là dessus.

**Comment by polomarcus** [comment]
On parlait d'utiliser la licence : "Public domain - CC0" : https://creativecommons.org/share-your-work/public-domain/cc0/ sur les données

![image](https://user-images.githubusercontent.com/4059615/95183195-e95bee80-07c5-11eb-862c-9a2259a6b867.png)

> La personne qui a associé une œuvre à cet acte a dédié l’œuvre au domaine public en renonçant dans le monde entier à ses droits sur l’œuvre selon les lois sur le droit d’auteur, droit voisin et connexes, dans la mesure permise par la loi.
> 
> Vous pouvez copier, modifier, distribuer et représenter l’œuvre, même à des fins commerciales, sans avoir besoin de demander l’autorisation. Voir d’autres informations ci-dessous.

source:  https://fr.wikipedia.org/wiki/Licence_CC0

avec votre accord je peux mettre à jour le site et les readme du repo concernant cette partie

**Comment by kentiss34** [comment]
Ok pour moi :+1:

**Comment by tounoki** [comment]
Faut vérifier la licence du logo "je suis un des 2" aussi si on met la licence sur la carte générée.
