### ISSUE TITLE
Gérer l'absence de fichier config.php

### ISSUE THREAD

**Issue by yoannsculo** [jesuisundesdeux/vigilo-backend#59]
L'absence de fichier config/config.php génère des erreurs php en cascade. Cela reste normal car le fichier est nécessaire au fonctionnement du backend. Toutefois, je pense qu'il serait intéressant de trouver un moyen de centraliser la gestion de son absence par un message d'erreur central plutôt qu'une cascade d'erreurs php de ce genre :

```
Warning: require_once(/var/www/html/includes/../config/config.php): failed to open stream: No such file or directory in /var/www/html/includes/common.php on line 22

Fatal error: require_once(): Failed opening required '/var/www/html/includes/../config/config.php' (include_path='.:/usr/local/lib/php') in /var/www/html/includes/common.php on line 22
```

**Comment by kentiss34** [comment]
Done
