### ISSUE TITLE
Ajouter un champ date de résolution

### ISSUE THREAD

**Issue by tcoupin** [jesuisundesdeux/vigilo-backend#67]
Quand le status passe à 1, il faudrait renseigner un champ status_update_time. La valeur peut être fournie dans un paramètre de la requête, ou renseigner par le temps courant si vide.

**Comment by kentiss34** [comment]
Du coup ajouter aussi (facultatif) :
- commentaire (50 caractères) : status_update_comment
- photo (booléen) : status_update_photo

**Comment by kentiss34** [comment]
Ajouté en 0.0.10

**Comment by kentiss34** [comment]
Voir #89
