### ISSUE TITLE
0.0.10 : Amélioration de la gestion des erreurs

### ISSUE THREAD

**Issue by yoannsculo** [jesuisundesdeux/vigilo-backend#78]
Je vous propose d'améliorer la gestion d'erreurs et de mettre en place un système générique qui fournirait plus d'informations en cas d'erreurs.

Voici donc le schéma que je proposerais :

Utiliser le code d'erreur HTTP (3XX, 4XX, 5XX suivant le type d'erreur) dans le header HTTP. C'est déjà le cas avec http_response_code(500) dans pas mal de scripts. Mais il ne faudra pas hésiter à utiliser les codes 4XX et 3XX en fonction des erreurs.

Cela ressemblerait à ça

```
{
    "error": {
        "status": 500, // Code HTTP
        "code": xxxx, // Code custom à choisir
        "type": "UneCategorieDerreur", // Catégorie à choisir parmis une liste à définir
        "message": "Message d'erreur compréhensible par un humain"
    }
}
```

De cette façon, nous pourrions adapter la fonction jsonError :

`jsonError($status, $code, $type, $error_msg)`

et toutes les erreurs seraient gérées de la même façon grâce à cette fonction.

Le message d'erreur serait écrit en Anglais, mais grâce au code custom, il pourrait être facilement transformé en message dans la langue de l'utilisateur de l'application.

Documentation à ce sujet

- https://nordicapis.com/best-practices-api-error-handling/
- https://blog.restcase.com/rest-api-error-codes-101/
- https://alidg.me/blog/2016/9/24/rest-api-error-handling

**Comment by kentiss34** [comment]
Tout à fait d'accord.
#TODO aussi : afficher ces erreurs coté applis clientes

**Comment by kentiss34** [comment]
Voir commit #99

**Comment by kentiss34** [comment]
#101
