### ISSUE TITLE
[REFLEXION] Résolutions observations

### ISSUE THREAD

**Issue by qhess34** [jesuisundesdeux/vigilo-backend#89]
J'ai rollbacké mes modifs concernant les status des obs.
Comme vu avec Yoann on va faire un truc plus basé sur une suite d'actions plutôt qu'un statut fixe.
Il faut donc créé une table (fait dans init-0.0.10.sql) qui stockera les actions effectuées.
Il faudrait définir le workflow à mettre en place selon le rôle.

Pour le moment j'identifie comme roles :
- Les collectivités
- Les admins/moderateurs
- Les autres (créateur observations / "invités" ) => A voir si on valide ce rôle

On peut lister un certains nombre de status :
- 0 : Nouvelle observation
- 1 : Observation prise en compte
- 2 : Observation en cours de résolution
- 3 : Observation indiqué comme résolue
- 4 : Observation résolue
- 5 : Observation avec résolution refusée

Selon le rôle on peut permettre certains statut ou pas.
- Les admin peuvent donner l'ensemble des statuts 
- Les collectivités : 1 / 2 / 3
- Les autres : 3

**Comment by kentiss34** [comment]
Commit #100

**Comment by yoannsculo** [comment]
J'ai réfléchi à la question et je pense que pour adresser ce sujet nous devons prendre encore un peu plus de recul sur Vigilo, son usage et sa finalité.

**Qu'est-ce qu'une résolution d'observation ?**
Que résout-on en définitive ? S'agit-il de la situation ou bien du cas particulier montré par l'observation ?
Si on prend une voiture garée sur le trottoir, peut-on résoudre la situation ? La situation sera t-elle résolue si la fourrière embarque la voiture ? Ou bien si plus de voiture ne vient se garer ici à l'avenir ?

Si je prends l'exemple de mon instance, c'est majoritairement du stationnement sur le trottoir. Est-ce que ces observations peuvent réellement être résolues ou même traitées par la ville ? Je ne pense pas.

Supposons toutefois que la ville décide d'installer des poteaux pour empêcher le stationnement de voitures. Peut-on envisager que la municipalité ouvrira tous les tickets de la rue pour les mettre en « résolus » ? J'ai du mal à l'imaginer.

Pour les problématique « type entretien » qui amènent clairement à une résolution, cela me semble par contre pertinent car on devine facilement les deux états (non résolu / résolu)
Exemples :
- un arbre couché
- un trou dans la chaussée
- des tessons de verre sur une piste cyclable
- un marquage au sol qui a disparu
- un panneau M12 dégradé

Pour la catégorie « absence d'aménagement », peut-on envisager une résolution individuelle des observations ? Supposons que pendant des mois les observations s'accumulent sur une piste cyclable mal conçue, la ville décide enfin de prendre en compte la demande. A ce moment là, que devons-nous faire ? Aller résoudre individuellement toutes les observations pour les marquer comme résolues ? Je ne pense pas que ça soit super pratique / faisable.

Cela vaut aussi pour le manque d'arceaux.

J'avais commencé à faire une diagramme d'état avec toutes les étapes et actions envisageables mais je pense que l'on prend le problème peut-être du mauvais côté.

Je pense que nous devons répondre aux questions suivantes avant d'aller plus loin

1. Quels types d'observations souhaitons-nous remonter dans Vigilo en tant qu'usagers / citoyens ? Nous avons besoin de préciser plus le scope actuel et voir si cela reste axé mobilités ou bien si nous pouvons étendre à plus (genre dépôt d'ordures, poubelle qui déborde, que sais-je...)
2. Quels sont les objectifs finaux de Vigilo, sa finalité ? Est-ce que nous nous y prenons bien pour aller dans ce sens ? Est-ce suffisamment constructif ? Ou bien trop frontal ?
3. Quels sont les besoins des villes ? Comment pouvons-nous y répondre de façon constructive ?
4. Veut-on travailler en bonne intelligence avec les villes, faire des compromis ? Ou bien souhaitons-nous être plus en mode rentre dedans en se disant « ASSEZ ! » ? (ma question n'est pas si absurde, c'est clairement un choix de philosophie du projet)
5. Une fois que l'on a décidé quelles catégories remonter dans Vigilo, il faut choisir quelles seraient les catégories binaires avec une possibilité de résolution. Mais je pense que ça ne pourra s'adapter qu'à seulement quelques types d'observations.

Autre idée comme ça, peut-on envisager de donner un accès au villes à Vigilo pour qu'ils postent eux mêmes des observations mais dans une optique de communication ? Exemple: voici de nouveaux arceaux, voici une nouvelle infrastructure, etc. Cela serait une autre catégorie utilisable uniquement par les villes, que l'on ne pourrait pas résoudre. Avec ce principe, pas besoin de « résoudre » les observations car les observations seraient purement à titre informatif. La résolution d'un problème passerait par une nouvelle observation postée par la municipalité.

Sinon pour terminer, après plus de trois mois d'usage de Vigilo je commence à voir que les municipalités commencent à regarder ce que l'on fait. Toutefois les usagers peuvent être assez véhéments dans leurs observations, ce qui s'explique. Mais faire travailler ces usagers à bout et les municipalités me semble être un sacré challenge ! C'est pourquoi je pense, à titre personnel, qu'il faudrait orienter Vigilo vers un outil le plus neutre possible et surtout qui puisse également résoudre les problèmes des municipalités, ce qui les pousseraient à s'intéresser plus à l'outil.

A mes yeux, ce qui pourrait marcher le plus serait d'arriver avec un outil neutre, factuel qui permet aux gens de remonter leurs problème mais également de résoudre les problèmes / besoins des municipalités.

**Comment by yoannsculo** [comment]
J'ai initié une [proposition d'évolution des catégories](https://github.com/jesuisundesdeux/vigilo-backend/issues/113) dans un autre ticket.

Pour en revenir aux comptes / rôles et rebondir sur ta proposition @kentiss34, je vois les comptes suivants :
- city-agent : agent munnicipal / employé de la mairie
- city-admin : par exemple responsable voirie / communication
- moderator : contributeur avancé, en mesure de valider et modifier des observations
- admin : personne qui administre l'instance de Vigilo, qui le maintient et le configure
- anonymous : contributeur qui envoie des observations depuis l'app

Se pose ensuite la question du compte utilisateur. Je vois deux philosophies.
- Soit nous restons 100% anonymes pour les contributions et cela reste un point important de Vigilo
- Soit nous permettons des remontées anonymes **et** des comptes utilisateurs authentifiés (pour celles et ceux qui le veulent uniquement) avec des fonctionnalités plus poussées.

Dans fonctionnalité plus poussée j'entends en vrac
- Pouvoir commenter une observation
- Pouvoir échanger avec la municipalité
- Pouvoir voter ? (Genre voter pour l'observation la plus dangereuse ou la plus prioritaire, etc.) Ce qui pourrait donner des informations intéressantes aux municipalités
- Pouvoir éditer son observation après coup ?
- Avoir un historique d'observations et éventuellement avoir une carte custom ou bien un export possible de ses propres photos.
- recevoir des news de l'application par email
- être informé par des mises à jours par la mairie ou bien des nouveaux aménagements, etc.
- ... les possibilotés sont infinies

Et donc dans cette seconde option, il y aurait alors un nouveau rôle, qui serait **user** et qui ne serait pas anonyme

**Comment by kentiss34** [comment]
Mes réponse :

**Quels types d'observations souhaitons-nous remonter dans Vigilo en tant qu'usagers / citoyens ? Nous avons besoin de préciser plus le scope actuel et voir si cela reste axé mobilités ou bien si nous pouvons étendre à plus (genre dépôt d'ordures, poubelle qui déborde, que sais-je...)**

Il ne faut pas fermer le débat sur l'extension du type d'observations. 
En outre pour le moment, il faut se restreindre à mon sens sur le sujet des mobilités actives.

**Quels sont les objectifs finaux de Vigilo, sa finalité ? Est-ce que nous nous y prenons bien pour aller dans ce sens ? Est-ce suffisamment constructif ? Ou bien trop frontal ?**

Vigilo est une application permettant de fournir des yeux partout sur le terrain avec les infos nécessaires pour donner de la visibilité sur les problèmes rencontrés. Son objectif n'est pas de proposer des solutions, mais de mettre en avant des problèmes.

**Quels sont les besoins des villes ? Comment pouvons-nous y répondre de façon constructive ?**

Il faut faire attention avec ça je pense. On ne travaille pas pour les villes mais pour les citoyens. 
On fournit les données brut, cartographiées et parfois même analysées.
Entre deux villes on risque en plus d'avoir des besoins différents.
Je réorienterais plutôt cette question vers : quels sont les besoins des associations pour pousser des projets et améliorations auprès des villes.

**Veut-on travailler en bonne intelligence avec les villes, faire des compromis ? Ou bien souhaitons-nous être plus en mode rentre dedans en se disant « ASSEZ ! » ? (ma question n'est pas si absurde, c'est clairement un choix de philosophie du projet)**

L'idée de base de l'appli c'est de faire du factuel citoyen. Les problèmes du quotidien ne sont pas politiques ils sont réels et doivent rester objectifs. A mon sens c'est pas au niveau de Vigilo lui même que la question doit se poser, mais du travail des assos dans la prise en compte des données.

**Une fois que l'on a décidé quelles catégories remonter dans Vigilo, il faut choisir quelles seraient les catégories binaires avec une possibilité de résolution. Mais je pense que ça ne pourra s'adapter qu'à seulement quelques types d'observations.**

Est-ce qu'au final les résolutions doivent faire parties de Vigilo ? 
Est-ce qu'une route réparée, des potelets ajoutés sur des pistes non respectées ne doivent pas déclencher un simple archivage de l'observation ("plus d'actualité" par exemple).

** Au sujet des rôles **

Pour moi il ne faut pas s'insérer dans le fonctionnement des mairies, on ne travaille pas pour elles et ça risque de passer pour de l'ingérence auprès de certains services.

Pour les fonctionnalités plus poussées c'est à voir.

**Comment by badele** [comment]
> **Qu'est-ce qu'une résolution d'observation ?**

Comme tu l'as dis, pour moi, il y'a 2 sortes de status.

1. Les status manuels
1. Les status automatiques

Il faudrait pour chaque catégories indiquer le type de status.

Ce qui permettrait pour les status automatiques d'indiquer un niveau de résolution automatiquement.

Par exemple à chaque ajout d'une observation de **stationnement gênant**, augmenter une jauge, si il y'a pas eu d'observation dans la journée, on diminue la jauge automatiquement. Si il y'a pas d'ajout d'observation du même type dans les jours suivant, la jauge diminue pour tomber à **zero == Résolue** 

Pour le cas d'une observation type **Défaut d'entretient**, cela peut être effectué manuellement, si les arbres ont étés taillés, on le signale manuellement. Mais ce n'est pas dit que ce soit la meilleure manière ! Car Il se peut que l'observation ai été ajouté sur un trajet occasionnel (l'observateur, n'y passera pas d'ici quelques semaine), il ne pourra donc vérifier par lui même que l'entretient ai été effectué.

De ce fait, les autres observateurs ne seront même pas au courant qu'une observation **Défaut d'entretient** avait été ajouté auparavant, il se pourrait donc que personne passe le status à **Résolue** . Je pense donc que dans ce genre de catégorie, on peut le seconder aussi d'un status automatique.

Je pense donc que le mieux est de passer tout status automatique et de sensibiliser les utilisateurs à ajouter les observations lorsque le problème persiste.

Car, vous le voyez bien, on vigilote lorsque on est géné(l'incivilité ou le défaut d'entretient nous a forcé à nous arrêter), dans le cas contraire, pourquoi s’arrêter quand tous roule :)
