### ISSUE TITLE
0.0.13 : Gestion des limitations villes

### ISSUE THREAD

**Issue by kentiss34** [jesuisundesdeux/vigilo-backend#92]
Pour suivi du chantier des limitations géographiques des villes.

Option 1 : Se baser sur le code postal => en place sur 0.0.10, non fonctionnel car Nominatim ne renvoi pas forcement un bon code et certaines villes on différents CP 
Option 2 : test areas MySQL => en cours
Option 3 : Se baser sur la ville envoyée par l'utilisateur (en ajoutant des contraintes coté applis clientes)

**Comment by kentiss34** [comment]
Work in progress
Les villes sont définies à partir de l'application

**Comment by kentiss34** [comment]
Creation d'un champs cityid (si la ville existe en base) + cityname (si elle n'existe pas pour historique) a partir de l'appli

**Comment by lenny64** [comment]
Salut @kentiss34 dans #138 j'ai voulu associer un citystaff à une ville, pour pouvoir mieux mettre en évidence les observations qui lui sont associées. Je compare par rapport à plusieurs champs mais idéalement il faudrait n'avoir à comparer que les city_id entre eux.
N'ayant pas le champ "obs_cityname" dans la table "obs_list" ça m'a permis de voir qu'il faudra faire attention à la compatibilité entre les backends qui ont le champ "obs_cityname" et ceux qui ne l'ont pas. En effet que se passe-t-il si l'application veut insérer un obs_cityname dans un backend en version <0.0.13 ?
@+ !

**Comment by kentiss34** [comment]
Hello,
L'application android envoi cityname ou cityid à partir de la version du backend 0.0.13 sinon elle garde la ville dans l'adresse complète qu'elle envoi comme maintenant.
