### ISSUE TITLE
0.0.10 : Corruption de jpeg à la soumission d'observation

### ISSUE THREAD

**Issue by yoannsculo** [jesuisundesdeux/vigilo-backend#93]
J'ai remarqué plusieurs cas de problèmes d'upload d'image via l'application web (vigilo-webapp-1.3.0) et le backend 0.0.9.
En récupérant la photo originale sur le serveur, je peux détecter avec

`identify -verbose ZJDGGW9V.jpg`

```
identify-im6.q16: Premature end of JPEG file `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: premature end of data segment `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST2 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST3 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST4 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST5 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST6 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST7 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST0 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST1 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST2 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify-im6.q16: Corrupt JPEG data: found marker 0xd9 instead of RST3 `ZJDGGW9V.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
```

que la photo est corrompue. J'aurais donc tendance à proposer un mécanisme côté backend pour tester l'intégrité de l'image avant de la soumettre. Je ne sais pas encore comment, mais si on peut le faire en ligne de commande facilement, on doit pouvoir le faire en php pour checker que le jpeg est ok.

**La photo originale**
![ZJDGGW9V](https://user-images.githubusercontent.com/691328/59661299-c9f11a80-91aa-11e9-8d39-a1e4a159c99d.jpg)

**L'observation finale**
![generate_panel php](https://user-images.githubusercontent.com/691328/59661330-e42af880-91aa-11e9-93be-72ef09787ff1.jpeg)

**Comment by kentiss34** [comment]
A priori on peut ça coté PHP
https://stackoverflow.com/questions/48021839/how-to-check-image-corrupt-or-not-in-php

Si l'image est integre on passe obs_complete à 1, sinon on le laisse à 0 et on renvoi une erreur

**Comment by kentiss34** [comment]
#96

**Comment by kentiss34** [comment]
Fait coté backend
